name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Build
        run: cd build && make
      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build
      - name: Restore executable permissions
        run: chmod +x build/* || true
      - name: Run tests
        run: cd build && ./fsm_test